version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 5
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/frontend-ng"
      - "/backend"
    cooldown:
      default-days: 5
    schedule:
      interval: "weekly"
    groups:
      npm-updates:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "docker"
    directories:
      - "/frontend-ng"
      - "/backend"
    cooldown:
      default-days: 5
    schedule:
      interval: "weekly"
    groups:
      docker-updates:
        update-types:
          - "patch"
          - "minor"
