sudo: required

services:
  - docker

before_install:
  - docker --version
  - docker build -t trafex/clipboard-backend -f Dockerfile-backend .
  - docker build -t trafex/clipboard-frontend -f Dockerfile-frontend .

script:
  - docker run --rm trafex/clipboard-frontend yarn lint
  - docker run --rm trafex/clipboard-frontend yarn test-coverage
  - docker run --rm trafex/clipboard-frontend yarn build
