sudo: required

services:
  - docker

before_install:
  - docker --version
  - docker build -t trafex/clipboard-backend -f Dockerfile-backend .
  - docker build -t trafex/clipboard-frontend -f Dockerfile-frontend .

# @todo: Add Flow when https://github.com/facebook/flow/issues/3649 is resolved
script:
  - docker run --rm trafex/clipboard-frontend yarn lint
  - docker run --rm trafex/clipboard-frontend yarn test-coverage
  - docker run --rm -v `pwd`/build:/usr/src/app/build trafex/clipboard-frontend yarn build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "clipboard.ninja"
  skip_cleanup: true
  local_dir: build
  region: "eu-west-1"
